[Service]
WorkingDirectory=/home/tysbox/HQ_Linux_Music_Player/frontend/.next/standalone
ExecStart=
ExecStart=/home/tysbox/.local/nodejs/bin/node /home/tysbox/HQ_Linux_Music_Player/frontend/.next/standalone/server.js