music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
db_file "/var/lib/mpd/tag_cache"
#log_file "/var/log/mpd/mpd.log"
log_level "verbose"
#pid_file "/run/mpd/pid"
state_file "/var/lib/mpd/state"
sticker_file "/var/lib/mpd/sticker.sql"
bind_to_address "127.0.0.1"
port "6600"



audio_output {
    type            "alsa"
    name            "ALSA Loopback"
    device          "hw:Loopback,0,0"
    format          "192000:32:2"
    mixer_type      "software"
}

audio_output {
    type            "alsa"
    name            "USB DAC"
    device          "plughw:2,0"
    mixer_type      "software"
}

audio_output {
    type            "alsa"
    name            "PC Speakers"
    device          "plughw:1,0"
    mixer_type      "software"
}

audio_output {
    type            "alsa"
    name            "Bluetooth"
    device          "plug:bluealsa"
    mixer_type      "software"
}
